metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOST}"]
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"
  ssl:
    certificate_authorities: ["/setup/certs/ca.crt"]

setup.kibana:
  host: "${KIBANA_HOSTS}"


processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~
  - add_cloud_metadata: ~
  - add_fields:
      target: ''
      fields:
        host.name: "nos3-metricbeat"

